### ISSUE TITLE
Create a UI for password changes

### ISSUE THREAD

**Issue by thomas-schroderadveq** [leupibr/trrrakk#30]
**Is your feature request related to a problem? Please describe.**
For users without a Gmail account: it would be nice to be provided with a username and dummy password that can then be modified by the user, so that privacy is preserved.

**Describe the solution you'd like**
Create a UI that allows the user to modify his/her password after the first login.

**Comment by leupibr** [comment]
@thomas-schroderadveq currently there's no possibility to self-register without a Google account. I'll create a ticket for that too. Further I will also create a ticket for SSO/Signup with a Github account which could be a real alternative to Google.

The password UI should only be a last resort, as the SSO feature of the big providers are much more secure than a custom implementation. However, it could be a use case under certain circumstances and I'll include it into the next release.

**Comment by leupibr** [comment]
See #31 and #32 for up vote and/or subscription.
